#!/bin/bash
set -e

/bin/rm -rf "/Library/OFX/Plugins/BuckswoodFilmEmulation.ofx.bundle"

CONSOLE_USER="$(/usr/bin/stat -f %Su /dev/console 2>/dev/null || true)"
if [ -n "$CONSOLE_USER" ] && [ "$CONSOLE_USER" != "root" ]; then
    /bin/rm -rf "/Users/$CONSOLE_USER/Library/OFX/Plugins/BuckswoodFilmEmulation.ofx.bundle"
fi

exit 0
